//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmTagProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MASTERALARMEntities : DbContext
    {
        public MASTERALARMEntities()
            : base("name=MASTERALARMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAlarmField> tblAlarmFields { get; set; }
        public virtual DbSet<tblAlarmFieldsData> tblAlarmFieldsDatas { get; set; }
        public virtual DbSet<tblAlarmsMaster> tblAlarmsMasters { get; set; }
        public virtual DbSet<tbl_AlarmMasterExceptionLogging> tbl_AlarmMasterExceptionLogging { get; set; }
        public virtual DbSet<tbl_AlarmMasterEventAuditLog> tbl_AlarmMasterEventAuditLog { get; set; }
        public virtual DbSet<tblAlarmsMasterBookinImport> tblAlarmsMasterBookinImports { get; set; }
    
        public virtual ObjectResult<TESTDATA_Result> TESTDATA(string searchTerm, string site, string status, Nullable<int> itemsPerPage, Nullable<int> page, ObjectParameter totalPages, ObjectParameter totRows, Nullable<int> numberOfPagesToReturn)
        {
            var searchTermParameter = searchTerm != null ?
                new ObjectParameter("SearchTerm", searchTerm) :
                new ObjectParameter("SearchTerm", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var numberOfPagesToReturnParameter = numberOfPagesToReturn.HasValue ?
                new ObjectParameter("NumberOfPagesToReturn", numberOfPagesToReturn) :
                new ObjectParameter("NumberOfPagesToReturn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TESTDATA_Result>("TESTDATA", searchTermParameter, siteParameter, statusParameter, itemsPerPageParameter, pageParameter, totalPages, totRows, numberOfPagesToReturnParameter);
        }
    
        public virtual ObjectResult<TESTDATATagDetails_Result> TESTDATATagDetails(string assTageName, string alarmType, string site)
        {
            var assTageNameParameter = assTageName != null ?
                new ObjectParameter("AssTageName", assTageName) :
                new ObjectParameter("AssTageName", typeof(string));
    
            var alarmTypeParameter = alarmType != null ?
                new ObjectParameter("AlarmType", alarmType) :
                new ObjectParameter("AlarmType", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TESTDATATagDetails_Result>("TESTDATATagDetails", assTageNameParameter, alarmTypeParameter, siteParameter);
        }
    
        public virtual ObjectResult<sp_AlarmSearch_Result> sp_AlarmSearch(string searchTerm, string site, string status, string tagStatus, Nullable<int> itemsPerPage, Nullable<int> page, Nullable<int> criteria, ObjectParameter totalPages, ObjectParameter totRows, Nullable<int> numberOfPagesToReturn)
        {
            var searchTermParameter = searchTerm != null ?
                new ObjectParameter("SearchTerm", searchTerm) :
                new ObjectParameter("SearchTerm", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var tagStatusParameter = tagStatus != null ?
                new ObjectParameter("TagStatus", tagStatus) :
                new ObjectParameter("TagStatus", typeof(string));
    
            var itemsPerPageParameter = itemsPerPage.HasValue ?
                new ObjectParameter("ItemsPerPage", itemsPerPage) :
                new ObjectParameter("ItemsPerPage", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            var numberOfPagesToReturnParameter = numberOfPagesToReturn.HasValue ?
                new ObjectParameter("NumberOfPagesToReturn", numberOfPagesToReturn) :
                new ObjectParameter("NumberOfPagesToReturn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AlarmSearch_Result>("sp_AlarmSearch", searchTermParameter, siteParameter, statusParameter, tagStatusParameter, itemsPerPageParameter, pageParameter, criteriaParameter, totalPages, totRows, numberOfPagesToReturnParameter);
        }
    
        public virtual ObjectResult<sp_AlarmTagDetails_Result> sp_AlarmTagDetails(string assTageName, string alarmType, string site)
        {
            var assTageNameParameter = assTageName != null ?
                new ObjectParameter("AssTageName", assTageName) :
                new ObjectParameter("AssTageName", typeof(string));
    
            var alarmTypeParameter = alarmType != null ?
                new ObjectParameter("AlarmType", alarmType) :
                new ObjectParameter("AlarmType", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AlarmTagDetails_Result>("sp_AlarmTagDetails", assTageNameParameter, alarmTypeParameter, siteParameter);
        }
    
        public virtual ObjectResult<sp_GetAllStatusList_Result> sp_GetAllStatusList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllStatusList_Result>("sp_GetAllStatusList");
        }
    
        public virtual ObjectResult<sp_GetSites_Result> sp_GetSites()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSites_Result>("sp_GetSites");
        }
    
        public virtual ObjectResult<masterAlarmDB_sp_GetAllTagStatus_Result> masterAlarmDB_sp_GetAllTagStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<masterAlarmDB_sp_GetAllTagStatus_Result>("masterAlarmDB_sp_GetAllTagStatus");
        }
    
        public virtual ObjectResult<masterAlarmDB_sp_BookinAlarmTags_Result> masterAlarmDB_sp_BookinAlarmTags(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<masterAlarmDB_sp_BookinAlarmTags_Result>("masterAlarmDB_sp_BookinAlarmTags", usernameParameter);
        }
    
        public virtual int masterAlarmDB_sp_BookinLoadOfflineData(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("masterAlarmDB_sp_BookinLoadOfflineData", usernameParameter);
        }
    
        public virtual ObjectResult<masterAlarmDB_sp_ExportReport_Result> masterAlarmDB_sp_ExportReport(string searchTerm, string site, string status, string tagStatus, Nullable<int> criteria)
        {
            var searchTermParameter = searchTerm != null ?
                new ObjectParameter("SearchTerm", searchTerm) :
                new ObjectParameter("SearchTerm", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var tagStatusParameter = tagStatus != null ?
                new ObjectParameter("TagStatus", tagStatus) :
                new ObjectParameter("TagStatus", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<masterAlarmDB_sp_ExportReport_Result>("masterAlarmDB_sp_ExportReport", searchTermParameter, siteParameter, statusParameter, tagStatusParameter, criteriaParameter);
        }
    
        public virtual int masterAlarmDB_sp_BookinReset(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("masterAlarmDB_sp_BookinReset", usernameParameter);
        }
    
        public virtual ObjectResult<masterAlarmDB_sp_BookinShowData_Result> masterAlarmDB_sp_BookinShowData(Nullable<int> rowsPerPage, Nullable<int> pageIndex, string username, ObjectParameter totalPages, ObjectParameter totalRows, string dataType)
        {
            var rowsPerPageParameter = rowsPerPage.HasValue ?
                new ObjectParameter("RowsPerPage", rowsPerPage) :
                new ObjectParameter("RowsPerPage", typeof(int));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var dataTypeParameter = dataType != null ?
                new ObjectParameter("DataType", dataType) :
                new ObjectParameter("DataType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<masterAlarmDB_sp_BookinShowData_Result>("masterAlarmDB_sp_BookinShowData", rowsPerPageParameter, pageIndexParameter, usernameParameter, totalPages, totalRows, dataTypeParameter);
        }
    
        public virtual ObjectResult<sp_GetMasterFieldsData_Result> sp_GetMasterFieldsData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetMasterFieldsData_Result>("sp_GetMasterFieldsData");
        }
    
        public virtual int masterAlarmDB_sp_BookinCheckData(string username, ObjectParameter isTagBookedIn)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("masterAlarmDB_sp_BookinCheckData", usernameParameter, isTagBookedIn);
        }
    }
}
