//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmTagProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlarmFieldsData
    {
        public int FieldDataID { get; set; }
        public string Value { get; set; }
        public int FieldID { get; set; }
        public Nullable<int> Retain { get; set; }
    
        public virtual tblAlarmField tblAlarmField { get; set; }
    }
}
